PortalDeNoticias/PortalDeNoticias/Models/Noticia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalDeNoticias.Models
{
    public class Noticia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public DateTime Data { get; set; }
        public string Conteudo { get; set; }


        public void Salvar()
        {
            using (var session = DocumentStoreHolder.Store.OpenSession())
            {
                session.Store(this);
                session.SaveChanges();
            }

        }

        public List<Noticia> Listar()
        {
            using (var session = DocumentStoreHolder.Store.OpenSession())
            {
                return session.Query<Noticia>().ToList();
            }

        }
        public Noticia Buscar(int id)
        {

            using (var session = DocumentStoreHolder.Store.OpenSession())
            {
                var find = session.Load<Noticia>(id);
                if (find == null)
                    throw new Exception("Noticia Não encotrada!");
                return find;

            }

        }

        public void Delete(int id)
        {

            using (var session = DocumentStoreHolder.Store.OpenSession())
            {
                var news = session.Load<Noticia>(id);

                if (news.Equals(null))
                    throw new Exception("Noticia Não encotrada!");

                session.Delete(news);
                session.SaveChanges();

            }

        }




    }
}

PortalDeNoticias/PortalDeNoticias/Models/RepositorioDeNoticias.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortalDeNoticias.Models
{
    public class RepositorioDeNoticias
    {
        private static List<Noticia> noticias;
        public static List<Noticia> Noticias
        {
            get
            {
                if (noticias == null)
                    CriarNoticia();
                return noticias;
            }
        }

        private static void CriarNoticia()
        {
            noticias = new List<Noticia>();

            noticias.Add(new Noticia
            {
                Id = 1,
                Titulo = "Primeira noticia",
                Autor = "Thiago",
                Data = DateTime.Now,
                Conteudo = "Lorem ipsum dolor sit amet, " +
                "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore"
            });

            noticias.Add(new Noticia
            {
                Id = 2,
                Titulo = "Segunda noticia",
                Autor = "Thiago",
                Data = DateTime.Now,
                Conteudo = "Lorem ipsum dolor sit amet, " +
                "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore"
            });
            noticias.Add(new Noticia
            {
                Id = 3,
                Titulo = "Terceira noticia",
                Autor = "Thiago",
                Data = DateTime.Now,
                Conteudo = "Lorem ipsum dolor sit amet, " +
                "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore"
            });
            noticias.Add(new Noticia
            {
                Id = 4,
                Titulo = "Quarta noticia",
                Autor = "Thiago",
                Data = DateTime.Now,
                Conteudo = "Lorem ipsum dolor sit amet, " +
                "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore"
            });
            noticias.Add(new Noticia
            {
                Id = 5,
                Titulo = "Quinta noticia",
                Autor = "Thiago",
                Data = DateTime.Now,
                Conteudo = "Lorem ipsum dolor sit amet, " +
                "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore"
            });
        }
    }
}                                                          

PortalDeNoticias/PortalDeNoticias/Controllers/NoticiasController.cs
using PortalDeNoticias.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalDeNoticias.Controllers
{
    public class NoticiasController : Controller
    {
        private List<Noticia> _lista;

        // GET: Noticias
        public ActionResult Index()
        {
            _lista = new Noticia().Listar() ?? new List<Noticia>();
            return View(_lista);
        }
        public ActionResult Detalhes(int id)
        {
            _lista = new Noticia().Listar() ?? new List<Noticia>();

            var noticias = _lista
                                 .Where(c => c.Id == id).FirstOrDefault();
            return View(noticias);
        }
        public ActionResult Buscar(string texto)
        {

            ViewResult retorno;
            _lista = new Noticia().Listar() ?? new List<Noticia>();
            try
            {

                var codigo = Convert.ToInt32(texto);

                _lista.Add(new Noticia().Buscar(codigo));
            }
            catch (Exception)
            {
                _lista = _lista.Where(c => c.Titulo.Contains(texto)
                                          || c.Conteudo.Contains(texto)).ToList();
            }
            finally
            {
                retorno = View(_lista);
            }

            return retorno;

        }

        public ActionResult Novo(Noticia noticia)
        {
            if (!string.IsNullOrEmpty(noticia.Titulo))
                NovaNoticia(noticia);

            return View();
        }

        private void NovaNoticia(Noticia noticia)
        {
            noticia.Salvar();

        }
        public ActionResult Excluir(int id)
        {

            new Noticia().Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Editar(int id)
        {

            var noticia = new Noticia().Buscar(id);
            return View(noticia);
        }
        [HttpPost]
        public ActionResult Editar(Noticia noticia)
        {

            noticia.Salvar();
            return View(noticia);
        }
    }
}

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Buscar.cshtml
@model IEnumerable<PortalDeNoticias.Models.Noticia>

@{
    ViewBag.Title = "Buscar";
}



@foreach (var item in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title">@item.Titulo</p>
        </div>
        <div class="panel-body">
            <p>@item.Conteudo.Substring(0, 10) ...</p>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Ler Mais", "Detalhes", new { id = @item.Id }, new { @class = "btn btn-default" })
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar Para Pagina Principal", "Index")
        </div>
    </div>

}

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Deletar.cshtml
@model PortalDeNoticias.Models.Noticia

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Noticia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Conteudo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Conteudo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar Para Pagina Principal", "Index")
        </div>
    }
</div>

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Detalhes.cshtml
@model PortalDeNoticias.Models.Noticia

@{
    ViewBag.Title = "Detalhes";
}

<h2>@Model.Titulo</h2>

<p>Publicado por <strong> @Model.Autor</strong> em <strong>@Model.Data.ToString("dd/MM/yyyy")</strong></p>


<p>@Model.Conteudo</p>

<p>
    @Html.ActionLink("Voltar Para Pagina Principal", "Index")
</p>

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Editar.cshtml
@model PortalDeNoticias.Models.Noticia

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noticia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Conteudo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conteudo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conteudo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para Pagina Principal", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Index.cshtml
@model IEnumerable<PortalDeNoticias.Models.Noticia>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Nova Notícia", "Novo")
</p>

@foreach (var item in Model)
{
    <p>


    </p>
    <div class="panel panel-default">
        <div class="panel-heading">
            <p class="panel-title">@item.Titulo</p>
        </div>
        <div class="panel-body">
            <p>@item.Conteudo.Substring(0, 10) ...</p>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Ler Mais", "Detalhes", new { id = @item.Id }, new { @class = "btn btn-default" })
            @Html.ActionLink("Excluir Notícia", "Excluir", new { id = @item.Id }, new { @class = "btn btn-default" })
            @Html.ActionLink("Editar Notícia", "Editar", new { id = @item.Id }, new { @class = "btn btn-default" })
        </div>
    </div>

}

PortalDeNoticias/PortalDeNoticias/Views/Noticias/Novo.cshtml
@model PortalDeNoticias.Models.Noticia


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noticia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Conteudo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conteudo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conteudo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para Pagina Principal", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PortalDeNoticias/PortalDeNoticias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Portal de Noticias Thiago</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">

        <div class="jumbotron">
            <h1>Portal de Noticias</h1>
        </div>

        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Inicio", "Index", "Noticias", null, new { @class = "navbar-brand" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <p class="panel-title">Buscar Noticias</p>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("Buscar", "Noticias", FormMethod.Get))
                        {
                            <input type="text" class="form-control" name="texto" placeholder="Buscar por..." />
                        }
                    </div>

                </div>
            </div>

        </div>
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>


        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </div>
</body>
</html>